AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Stack de exemplo para o desafio DIO - Automatizando infraestrutura com AWS CloudFormation.
  Este template cria uma infraestrutura simples contendo um bucket S3 e uma instância EC2.

Parameters:
  Environment:
    Type: String
    Description: Ambiente de implantação (ex: dev, test, prod)
    Default: dev

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: infraestrutura-automatizada-juliao-20251031
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 (pode variar por região)
      Tags:
        - Key: Name
          Value: EC2-CloudFormation-${Environment}

Outputs:
  BucketName:
    Description: Nome do bucket criado
    Value: !Ref MeuBucketS3
  EC2InstanceId:
    Description: ID da instância EC2 criada
    Value: !Ref MinhaInstanciaEC2

